export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "JC Rodriguez",
  headline: "Text inserted will be big",
  description: "Small text that will be inserted on bottom on big text !",
  buttonLabel: "¡¡Contact me¡¡",
  imgStart: false,
  img: ("./images/dayplanner.JPG"),
  alt: "Picture",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjTwo = {
  id: "portfolio",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Portfolio",
  headline: "Text inserted will be big",
  description: "Small text that will be inserted on bottom on big text !",
  buttonLabel: "¡¡portfolio¡¡",
  imgStart: true,
  img: ("./images/desk.svg"),
  alt: "portfoliopics",
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjThree = {
  id: "contact",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Contact",
  headline: "Text inserted will be big",
  description: "Small text that will be inserted on bottom on big text !",
  buttonLabel: "¡¡Hello Contact¡¡",
  imgStart: false,
  img: ("./images/profilepic.JPG"),
  alt: "Me",
  dark: false,
  primary: false,
  darkText: true,
};
